export type LawRule = {
  id: string;
  category: string;
  title: string;
  law: string;
  fineMin: number;
  fineMax: number;
  howToCheck: string;
  realRiskLevel: "high" | "medium" | "low";
  enforcementNote?: string;
  lawArticle?: string;
  lastReviewed?: string;
};

const NOTE_HIGH = "РКН ведёт автоматический мониторинг сайтов с 2025 года. Штрафы по этой статье назначаются в судах в 2025–2026 годах регулярно.";
const NOTE_MEDIUM = "Юридический риск реальный, но массовых проверок РКН по этому составу пока не зафиксировано. Рекомендуется устранить как профилактическая мера.";
const NOTE_LOW = "Нарушение формальное, штрафы крайне редки. Имеет смысл устранить для общего качества, но риск проверки минимальный.";

export const LAWS: LawRule[] = [
  // 1. Персональные данные (152-ФЗ)
  {
    id: "pd-policy",
    category: "Персональные данные",
    title: "Отсутствует политика обработки персональных данных",
    law: "ст. 18.1 ФЗ-152",
    fineMin: 60000,
    fineMax: 100000,
    howToCheck: "Найти ссылку «Политика конфиденциальности» / «Политика обработки персональных данных»",
    realRiskLevel: "medium",
    enforcementNote: "Штраф 60–100 тыс. ₽, но РКН с 2024 года ведёт автоматический мониторинг и отсутствие политики — одна из самых частых причин предписаний. Устранить в первую очередь: без политики невозможно легально собирать любые данные через формы.",
    lawArticle: "ч. 3 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "pd-policy-link",
    category: "Персональные данные",
    title: "Политика опубликована, но недоступна с главной страницы",
    law: "ч. 2 ст. 18.1 ФЗ-152",
    fineMin: 60000,
    fineMax: 100000,
    howToCheck: "Ссылка должна быть в футере или подвале каждой страницы",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lawArticle: "ч. 3 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "pd-consent",
    category: "Персональные данные",
    title: "Нет согласия на обработку ПДн при отправке формы",
    law: "ст. 9 ФЗ-152",
    fineMin: 300000,
    fineMax: 700000,
    howToCheck: "У форм с телефоном/email должен быть чекбокс согласия и ссылка на политику",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 1 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "pd-cross-border",
    category: "Персональные данные",
    title: "Нет отдельного согласия на трансграничную передачу ПДн",
    law: "ст. 12 ФЗ-152",
    fineMin: 1000000,
    fineMax: 6000000,
    howToCheck: "Если используются Google/иностранные сервисы — нужно отдельное согласие",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 8 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "pd-localization",
    category: "Персональные данные",
    title: "ПДн россиян хранятся за пределами РФ",
    law: "ч. 5 ст. 18 ФЗ-152",
    fineMin: 1000000,
    fineMax: 6000000,
    howToCheck: "Хостинг и базы данных должны быть на территории РФ",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 8 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "pd-roskomnadzor",
    category: "Персональные данные",
    title: "Сайт не зарегистрирован в реестре операторов ПДн",
    law: "ч. 1 ст. 22 ФЗ-152",
    fineMin: 100000,
    fineMax: 300000,
    howToCheck: "Юрлицо/ИП должно быть в реестре Роскомнадзора",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lawArticle: "ст. 19.7 КоАП РФ",
    lastReviewed: "2026-05",
  },

  // 2. Cookies
  {
    id: "cookie-banner",
    category: "Cookies",
    title: "Отсутствует баннер согласия на использование cookies",
    law: "ст. 9 ФЗ-152",
    fineMin: 300000,
    fineMax: 700000,
    howToCheck: "При первом заходе должен быть баннер с кнопкой «Принять»",
    realRiskLevel: "high",
    enforcementNote: "Теоретический штраф высокий (300–700 тыс. ₽), но реальных дел именно за отсутствие cookie-баннера в России пока мало — РКН фокусируется на иностранных трекерах и локализации. Тем не менее риск растёт: с 2025 года идут проверки в связке «нет баннера + есть Google Analytics».",
    lawArticle: "ч. 1 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "cookie-russian",
    category: "Cookies",
    title: "Текст cookie-баннера только на иностранном языке",
    law: "ч. 2 ст. 3 ФЗ-53 «О государственном языке»",
    fineMin: 100000,
    fineMax: 500000,
    howToCheck: "Текст должен быть на русском или с переводом",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lawArticle: "ч. 2 ст. 3 ФЗ-53",
    lastReviewed: "2026-05",
  },
  {
    id: "cookie-passive",
    category: "Cookies",
    title: "Нет активного согласия — cookies ставятся до клика",
    law: "ст. 9 ФЗ-152",
    fineMin: 300000,
    fineMax: 700000,
    howToCheck: "До нажатия «Принять» технические/маркетинговые cookies ставиться не должны",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 1 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },

  // 3. Иностранные трекеры и сервисы
  {
    id: "google-analytics",
    category: "Иностранные сервисы",
    title: "Подключён Google Analytics без согласия и локализации ПДн",
    law: "ФЗ-152 + ФЗ-242",
    fineMin: 1000000,
    fineMax: 6000000,
    howToCheck: "Найти скрипт gtag, google-analytics.com, googletagmanager.com",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 8 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "google-fonts",
    category: "Иностранные сервисы",
    title: "Используется Google Fonts (передача IP за рубеж)",
    law: "ФЗ-152",
    fineMin: 60000,
    fineMax: 300000,
    howToCheck: "Найти ссылки fonts.googleapis.com или fonts.gstatic.com",
    realRiskLevel: "medium",
    enforcementNote: "Теоретически та же статья что у Google Analytics, но реальных дел именно за Google Fonts в России не зафиксировано. Устранить несложно: заменить на самохостинг шрифтов или Bunny Fonts (серверы в ЕС, но без передачи IP в Google).",
    lawArticle: "ч. 1 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "meta-ads-pixel",
    category: "Иностранные сервисы",
    title: "Признаки рекламной активности в Meta-соцсетях (Facebook Pixel, Conversions API)",
    law: "ст. 14.3 КоАП РФ (с 1.09.2025) + риск ст. 282.3 УК РФ",
    fineMin: 300000,
    fineMax: 1000000,
    howToCheck: "Найти connect.facebook.net, fbq(), события init/track Pixel",
    realRiskLevel: "high",
    enforcementNote: "С 1 сентября 2025 года реклама в Meta-соцсетях полностью запрещена. Установленный Facebook Pixel — индикатор активной кампании. Также есть риск уголовной квалификации как финансирование экстремизма (ст. 282.3 УК РФ).",
    lawArticle: "ст. 14.3 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "meta-logo",
    category: "Иностранные сервисы",
    title: "Логотип Instagram/Facebook на сайте (символика экстремистской организации)",
    law: "ст. 20.3 КоАП РФ",
    fineMin: 1000,
    fineMax: 50000,
    howToCheck: "Найти иконки fa-instagram/fa-facebook, файлы instagram.svg/facebook.svg, SVG с aria-label Instagram/Facebook",
    realRiskLevel: "high",
    enforcementNote: "Демонстрация символики запрещённой организации — реальные штрафы есть в практике 2022–2026 годов. Срочно убрать логотипы из шапки, подвала, кнопок «Поделиться».",
    lawArticle: "ст. 20.3 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "meta-links-text",
    category: "Иностранные сервисы",
    title: "Текстовое упоминание Instagram/Facebook без пометки об экстремистской организации",
    law: "ч. 2 ст. 13.15 КоАП РФ",
    fineMin: 4000,
    fineMax: 50000,
    howToCheck: "Найти 'instagram' или 'facebook' в тексте, проверить отсутствие пометки рядом",
    realRiskLevel: "low",
    enforcementNote: "Для обычных коммерческих сайтов реальной практики штрафов почти нет — обычно выносится предупреждение от прокуратуры. Высокий риск только для СМИ и публичных персон с большой аудиторией.",
    lawArticle: "ч. 2 ст. 13.15 КоАП РФ",
    lastReviewed: "2026-05",
  },

  // 4. Рекламное законодательство
  {
    id: "ad-marker",
    category: "Реклама",
    title: "Реклама без маркировки «Реклама» и токена ОРД",
    law: "ст. 18.1 ФЗ-38 «О рекламе»",
    fineMin: 200000,
    fineMax: 500000,
    howToCheck: "У всех рекламных блоков должна быть пометка «Реклама» и erid-токен",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ст. 14.3 ч. 16 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "ad-best",
    category: "Реклама",
    title: "Используются формулировки «лучший», «№1», «единственный» без подтверждения",
    law: "ч. 1 ст. 5 ФЗ-38",
    fineMin: 100000,
    fineMax: 500000,
    howToCheck: "Превосходные степени без ссылки на исследование запрещены",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lawArticle: "ст. 14.3 ч. 1 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "ad-medical",
    category: "Реклама",
    title: "Реклама медуслуг без предупреждения о противопоказаниях",
    law: "ч. 7 ст. 24 ФЗ-38",
    fineMin: 200000,
    fineMax: 500000,
    howToCheck: "Должна быть фраза о консультации специалиста и противопоказаниях",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ст. 14.3.1 КоАП РФ",
    lastReviewed: "2026-05",
  },

  // 5. Государственный язык
  {
    id: "lang-anglicisms",
    category: "Государственный язык",
    title: "Англицизмы и иностранные слова без перевода",
    law: "ФЗ-53 «О государственном языке РФ»",
    fineMin: 40000,
    fineMax: 100000,
    howToCheck: "Слова типа sale, new, premium, contact us — нужны переводы или замена",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lawArticle: "ст. 28.1 ФЗ-53",
    lastReviewed: "2026-05",
  },
  {
    id: "lang-headers",
    category: "Государственный язык",
    title: "Заголовки и навигация на иностранном языке",
    law: "ч. 2 ст. 3 ФЗ-53",
    fineMin: 40000,
    fineMax: 100000,
    howToCheck: "Меню «Home / About / Contacts» — нарушение",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lawArticle: "ч. 2 ст. 3 ФЗ-53",
    lastReviewed: "2026-05",
  },

  // 6. Реквизиты юрлица
  {
    id: "req-company",
    category: "Реквизиты",
    title: "Не указано полное наименование организации/ИП",
    law: "ст. 9 ФЗ «О защите прав потребителей»",
    fineMin: 5000,
    fineMax: 10000,
    howToCheck: "В подвале должно быть ООО/ИП + полное название",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },
  {
    id: "req-inn",
    category: "Реквизиты",
    title: "Не указан ИНН и ОГРН/ОГРНИП",
    law: "ст. 9 ФЗ «О защите прав потребителей»",
    fineMin: 5000,
    fineMax: 10000,
    howToCheck: "В контактах должны быть ИНН и ОГРН",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },
  {
    id: "req-address",
    category: "Реквизиты",
    title: "Не указан физический адрес юрлица",
    law: "ст. 9 ФЗ «О защите прав потребителей»",
    fineMin: 5000,
    fineMax: 10000,
    howToCheck: "Адрес регистрации должен быть на странице контактов",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },

  // 7. Публичная оферта
  {
    id: "offer",
    category: "Договоры",
    title: "Отсутствует публичная оферта при онлайн-продажах",
    law: "ст. 437 ГК РФ",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "При наличии корзины/оплаты — должна быть оферта",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lastReviewed: "2026-05",
  },
  {
    id: "user-agreement",
    category: "Договоры",
    title: "Нет пользовательского соглашения",
    law: "ГК РФ",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "Особенно для сервисов с регистрацией",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lastReviewed: "2026-05",
  },

  // 8. Защита прав потребителей
  {
    id: "zpp-return",
    category: "Права потребителей",
    title: "Не указаны условия возврата товара/услуги",
    law: "ст. 26.1 ФЗ «О защите прав потребителей»",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "Должен быть раздел про возврат",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },
  {
    id: "zpp-warranty",
    category: "Права потребителей",
    title: "Нет информации о гарантии",
    law: "ст. 19 ФЗ «О защите прав потребителей»",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "Срок гарантии должен быть указан",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },

  // 9. Доступность для слабовидящих
  {
    id: "a11y-version",
    category: "Доступность",
    title: "Нет версии для слабовидящих",
    law: "ст. 14 ФЗ-181 «О соцзащите инвалидов»",
    fineMin: 30000,
    fineMax: 100000,
    howToCheck: "Кнопка переключения на крупный шрифт / контрастный режим",
    realRiskLevel: "low",
    enforcementNote: NOTE_LOW,
    lastReviewed: "2026-05",
  },

  // 10. Возрастная маркировка
  {
    id: "age-marker",
    category: "Возрастная маркировка",
    title: "Отсутствует возрастная маркировка (для СМИ и сайтов с медиаконтентом)",
    law: "ст. 11 ФЗ-436",
    fineMin: 20000,
    fineMax: 200000,
    howToCheck: "Применимо только к сетевым изданиям (СМИ) и сайтам, распространяющим книги/фильмы/игры. Обычные коммерческие сайты маркировку не обязаны ставить.",
    realRiskLevel: "low",
    enforcementNote: "Требование распространяется только на зарегистрированные СМИ и ресурсы с медиаконтентом (фильмы, книги, игры). Для обычного коммерческого сайта, блога или визитки — не применяется.",
    lastReviewed: "2026-05",
  },

  // 11. Регистрация в реестре блогеров / Роскомнадзоре
  {
    id: "rkn-blogger",
    category: "Реестры РКН",
    title: "Сайт >10 000 посещений/сутки не зарегистрирован как СМИ/блогер",
    law: "ст. 10.2 ФЗ-149",
    fineMin: 10000,
    fineMax: 300000,
    howToCheck: "При большой посещаемости нужна регистрация",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lastReviewed: "2026-05",
  },

  // 12. Упоминание запрещённых организаций
  {
    id: "extremist",
    category: "Запрещённые упоминания",
    title: "Упоминание запрещённых организаций без пометки",
    law: "ст. 13.15 КоАП РФ",
    fineMin: 100000,
    fineMax: 500000,
    howToCheck: "Нужна пометка о статусе организации",
    realRiskLevel: "medium",
    enforcementNote: NOTE_MEDIUM,
    lastReviewed: "2026-05",
  },

  // 13. Обратная связь и контакты
  {
    id: "contact-form",
    category: "Обратная связь",
    title: "В формах обратной связи нет ссылки на политику ПДн",
    law: "ст. 9 ФЗ-152",
    fineMin: 300000,
    fineMax: 700000,
    howToCheck: "Под кнопкой «Отправить» — текст с согласием и ссылкой",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lawArticle: "ч. 1 ст. 13.11 КоАП РФ",
    lastReviewed: "2026-05",
  },

  // 14. Запрещённый контент
  {
    id: "lgbt",
    category: "Запрещённый контент",
    title: "Пропаганда ЛГБТ (признано экстремистским движением)",
    law: "ст. 6.21 КоАП РФ",
    fineMin: 50000,
    fineMax: 5000000,
    howToCheck: "Любые упоминания/символика без явного осуждения",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lastReviewed: "2026-05",
  },
  {
    id: "drugs",
    category: "Запрещённый контент",
    title: "Информация о наркотических средствах",
    law: "ст. 6.13 КоАП РФ",
    fineMin: 800000,
    fineMax: 1500000,
    howToCheck: "Любые описания, инструкции, ссылки",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lastReviewed: "2026-05",
  },
  {
    id: "suicide",
    category: "Запрещённый контент",
    title: "Описание способов суицида",
    law: "ст. 6.21.1 КоАП РФ",
    fineMin: 50000,
    fineMax: 500000,
    howToCheck: "Любые методы и инструкции",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lastReviewed: "2026-05",
  },

  // 15. Реквизиты и ЗоЗПП (коммерческие сайты)
  {
    id: "requisites-missing",
    category: "Реквизиты юр.лица",
    title: "Не указаны реквизиты юридического лица (ИНН, ОГРН, адрес, наименование)",
    law: "ст. 9 ЗоЗПП, ч. 1 ст. 14.5 КоАП РФ",
    fineMin: 30000,
    fineMax: 40000,
    howToCheck: "Поиск ИНН, ОГРН, названия юр.лица в footer или на странице Контакты/Реквизиты",
    realRiskLevel: "low",
    enforcementNote: "Штраф небольшой (30–40 тыс. ₽). Роспотребнадзор проверяет в основном при поступлении жалоб от потребителей, массовых плановых проверок сайтов по этому основанию нет. Рекомендуется устранить, но угрозы крупного штрафа нет.",
    lawArticle: "ч. 1 ст. 14.5 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "offer-missing",
    category: "Документы продавца",
    title: "Публичная оферта или условия использования не найдены",
    law: "ст. 435–437 ГК РФ, ст. 26.1 ЗоЗПП",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "Ссылка с текстом «оферта», «договор-оферта», «условия продажи» в footer (только для коммерческих сайтов)",
    realRiskLevel: "low",
    enforcementNote: "Штраф небольшой (10–30 тыс. ₽). Роспотребнадзор применяет это основание при жалобах покупателей, не в рамках плановых проверок сайтов.",
    lastReviewed: "2026-05",
  },
  {
    id: "return-policy-missing",
    category: "Документы продавца",
    title: "Условия возврата товара не указаны (для интернет-магазинов)",
    law: "ст. 26.1 ЗоЗПП",
    fineMin: 10000,
    fineMax: 30000,
    howToCheck: "Ссылка с текстом «возврат», «обмен», «гарантия товара» в footer (только для коммерческих сайтов)",
    realRiskLevel: "low",
    enforcementNote: "Штраф небольшой (10–30 тыс. ₽). Важно с точки зрения прав потребителей, но крупных санкций не влечёт. Устранить несложно — достаточно страницы с описанием условий возврата.",
    lastReviewed: "2026-05",
  },
  {
    id: "contacts-missing",
    category: "Реквизиты юр.лица",
    title: "Контактная информация (телефон или email) не указана",
    law: "ст. 8 ЗоЗПП, ч. 1 ст. 14.8 КоАП РФ",
    fineMin: 5000,
    fineMax: 10000,
    howToCheck: "Поиск номера телефона (+7/8) или email-адреса в footer или на странице Контакты",
    realRiskLevel: "low",
    enforcementNote: "Минимальные требования по контактам обычно соблюдаются. Штрафы по этому пункту крайне редки.",
    lawArticle: "ч. 1 ст. 14.8 КоАП РФ",
    lastReviewed: "2026-05",
  },
  {
    id: "prices-currency",
    category: "Цены и оферта",
    title: "Цены указаны не в рублях",
    law: "ст. 10 ЗоЗПП",
    fineMin: 5000,
    fineMax: 10000,
    howToCheck: "Найти ценники, проверить наличие ₽/руб/RUB рядом с числами (только для коммерческих сайтов)",
    realRiskLevel: "low",
    enforcementNote: "Цены обязательно должны быть в рублях. Нарушение только когда рубли отсутствуют совсем.",
    lastReviewed: "2026-05",
  },

  // 16. SSL и безопасность
  {
    id: "ssl",
    category: "Безопасность",
    title: "Сайт работает без HTTPS / с просроченным сертификатом",
    law: "ст. 19 ФЗ-152 (требование защиты ПДн)",
    fineMin: 30000,
    fineMax: 100000,
    howToCheck: "Адрес должен начинаться с https://, сертификат действителен",
    realRiskLevel: "high",
    enforcementNote: NOTE_HIGH,
    lastReviewed: "2026-05",
  },
];

export const TOTAL_RULES = LAWS.length;
export const TOTAL_CATEGORIES = new Set(LAWS.map((l) => l.category)).size;
